---
- name: Check cert exists
  stat:
    path: /etc/kubernetes/pki/etcd/ca.crt
  register: ca_cert

- name: Copy etcd service manager config
  copy:
    src: "{{ role_path }}/files/20-etcd-service-manager.conf"
    dest: /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf
  when: ca_cert.stat.exists == false

- name: Create kubeadm config
  template:
    src: "{{ role_path }}/templates/kubeadmcfg.etcd-setup.yaml.j2"
    dest: /tmp/kubeadmcfg.etcd-setup.yaml
  when: ca_cert.stat.exists == false

- name: Ensure kubernetes pki etcd directory exists
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory
  when: ca_cert.stat.exists == false

- name: Generate ca certs (master)
  shell: kubeadm init phase certs etcd-ca
  when: gen_ca_certs == true and ca_cert.stat.exists == false

- name: Fetch ca.crt from etcd-ca group
  fetch:
    src: /etc/kubernetes/pki/etcd/ca.crt
    dest: /tmp/ca.crt
    flat: yes
  when: gen_ca_certs == true and ca_cert.stat.exists == false

- name: Fetch ca.key from etcd-ca group
  fetch:
    src: /etc/kubernetes/pki/etcd/ca.key
    dest: /tmp/ca.key
    flat: yes
  when: gen_ca_certs == true and ca_cert.stat.exists == false

- name: Copy ca.crt to etcd group
  copy:
    src: /tmp/ca.crt
    dest: /etc/kubernetes/pki/etcd/ca.crt
  when: gen_ca_certs == false and ca_cert.stat.exists == false

- name: Copy ca.key to etcd group
  copy:
    src: /tmp/ca.key
    dest: /etc/kubernetes/pki/etcd/ca.key
  when: gen_ca_certs == false and ca_cert.stat.exists == false

- name: Create etcd certs
  shell: |
    kubeadm init phase certs etcd-server --config=/tmp/kubeadmcfg.etcd-setup.yaml
    kubeadm init phase certs etcd-peer --config=/tmp/kubeadmcfg.etcd-setup.yaml
    kubeadm init phase certs etcd-healthcheck-client --config=/tmp/kubeadmcfg.etcd-setup.yaml
    kubeadm init phase certs apiserver-etcd-client --config=/tmp/kubeadmcfg.etcd-setup.yaml
  when: ca_cert.stat.exists == false

- name: Remove ca.key from etcd group
  file:
    path: /etc/kubernetes/pki/etcd/ca.key
    state: absent
  when: gen_ca_certs == false and ca_cert.stat.exists == false

- name: Create etcd manifests
  shell: kubeadm init phase etcd local --config=/tmp/kubeadmcfg.etcd-setup.yaml
  when: ca_cert.stat.exists == false

- name: Set etcd container image
  replace:
    destfile: /etc/kubernetes/manifests/etcd.yaml
    regexp: '(\s+)image: k8s\.gcr\.io/etcd:3\.2\.24(\s+.*)?$'
    replace: '\1image: {{ etcd_image }}:{{ etcd_tag }}\2'
  notify:
    - Restart kubelet
  when: ca_cert.stat.exists == false

- name: Remove etcd setup kubeadmcfg
  file:
    path: /tmp/kubeadmcfg.etcd-setup.yaml
    state: absent
