---
- name: Ensure kubernetes pki etcd directory exists
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory

- name: Fetch ca.crt from etcd-ca group
  fetch:
    src: /etc/kubernetes/pki/etcd/ca.key
    dest: /tmp/ca.key
    flat: yes
  delegate_to: "{{ hostvars[groups['etcd-ca'][0]].ansible_hostname }}"

- name: Copy ca.crt to master
  copy:
    src: /tmp/ca.crt
    dest: /etc/kubernetes/pki/etcd/ca.crt

- name: Generate bootstrap token
  shell: kubeadm token generate
  register: kubeadm_token

- set_fact:
    bootstrap_token: kubeadm_token.stdout

- name: Create kubeadm config
  template:
    src: "{{ role_path }}/templates/kubeadm-config.yaml.j2"
    dest: /tmp/kubeadm-config.yaml

- name: Initialise kubeadm
  shell: kubeadm init --config /tmp/kubeadm-config.yaml

- name: Apply weave plugin for networking
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

- name: Remove kubeadm-config
  file:
    path: /tmp/kubeadm-config.yaml
    state: absent
