---
- name: Ensure kubernetes pki etcd directory exists
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory

- name: Copy etcd ca cert from etcd-ca to master
  synchronize:
    src: /etc/kubernetes/pki/etcd/ca.crt
    dest: /etc/kubernetes/pki/etcd/ca.crt
  delegate_to: etcd-ca

- name: Create kubeadm config
  template:
    src: "{{ role_path }}/templates/kubeadm-config.j2"
    dest: /tmp/kubeadm-config.yaml

- name: Generate bootstrap token
  shell: kubeadm token generate
  register: kubeadm_token

- set_fact:
    bootstrap_token: kubeadm_token.stdout

- name: Initialise kubeadm
  shell: kubeadm init --config /tmp/kubeadm-config.yaml --token {{ bootstrap_token }}

- name: Apply weave plugin for networking
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

- name: Remove kubeadm-config
  file:
    path: /tmp/kubeadm-config.yaml
    state: absent
